[options]
db_template = odoo_template
addons_path = addons,C:\Users\hutha\Desktop\Odoo\odoo\odoo\addons,C:\Users\hutha\Desktop\Odoo\odoo_ent_16\odoo\addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
wkhtmltopdf = "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
admin_passwd = $pbkdf2-sha512$600000$J8TY.5.Tci7FeI9xLmWslQ$CAcynXcUeHaKbh9qKUjSZqQze/Msi.SGSP803WAZcS1c5Rd.KoLAMo3lPXmdDTjS4DM7AobhG39JlzW4FTXxSw

