[options]
db_template = odoo_template
addons_path = C:\Users\hutha\Desktop\Odoo\odoo_ent_16\odoo\addons, C:\Users\hutha\Desktop\Odoo\odoo\addons, C:\Users\hutha\Desktop\Odoo\odoo\odoo\addons, C:\Users\hutha\Desktop\Odoo\odoo_EN_16, C:\Users\hutha\Desktop\Odoo\nasercenter_dev, C:\Users\hutha\Desktop\Odoo\falakj_transfer_16, C:\Users\hutha\Desktop\Odoo\pos_dev_16
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
log_level = debug
wkhtmltopdf = "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
admin_passwd = $pbkdf2-sha512$600000$mJOSkrL2npOyFiLE2LvXeg$dPvOOoQVyuqJeofixraznJXe7zBi9/lWngoeLdBHkRUjKjRR.abIwSVsloyVjwLsElT/du3Gy7RGKPAMbnQuZA

