[options]
db_template = odoo_template
addons_path = C:\Users\hutha\Desktop\Odoo\odoo-19.0+e\odoo\addons, addons,C:\Users\hutha\Desktop\Odoo\odoo\odoo\addons, C:\Users\hutha\Desktop\Odoo\multi_branches_16, C:\Users\hutha\Desktop\Odoo\odoo_EN_16
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
log_level = debug
wkhtmltopdf = "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
admin_passwd = $pbkdf2-sha512$600000$fE/J.X/POSfE.J.ztrb23g$w25dmC8rCo3Pxm3akJB0CmbRVjkT30V8a8.jHBRf9FX.69HRWjn/F2z1quM9h.xDwFfCc6.6UY4dAzwjForTMQ
